# Generated by Django 5.1.1 on 2024-09-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
